dist: xenial
sudo: false
latex: false
language: r
r: release
warnings_are_errors: false
cache:
    packages: true
    apt_packages:
    - libgdal-dev
    - libudunits2-dev
git:
    depth: false
r_packages:
  - rsconnect
  - shiny
  - leaflet
  - dplyr
  - tidyr
  - tidyverse
  - mosaic
  - rnoaa
  - shinyWidgets
  - taxize
  - AOI
  - climateR
  - rgeos
  - sf
  - raster
  - rasterVis
  - sp
  - tidyverse
  - rgdal

script:
    - R -f deploy.R
